UP = 38
DOWN = 40
RIGHT = 39
LEFT = 37
SPACE = 32
SCORE = document.getElementById('score')
HEALTH = document.getElementById('health')
MYHEALTH = document.querySelector("#healthBar > div")
LIVES = document.getElementById('lives')